# Generated by Django 4.2.30 on 2026-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_technique', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=100)),
                ('titres', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('victoires', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('img_url', models.URLField(blank=True, max_length=1000)),
            ],
        ),
    ]
